### ISSUE TITLE
Validator failing basic config

### ISSUE THREAD

**Issue by fatmcgav** [garethjevans/jcasc-validator#33]
Hey there,

Firstly, thanks for putting this project together. We're in the process of migrating our Jenkins controllers to JCasC and being able to validate changes before deploying them is a vital piece of that puzzle...

I've had a play around, and I'm getting some unusual results.

Given the following `base.yaml` file:
```yaml
jenkins:
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disabledAdministrativeMonitors:
    - jenkins.security.s2m.MasterKillSwitchWarning
  disableRememberMe: false
  globalNodeProperties:
    - envVars:
        env:
          - key: JENKINS_CLUSTER_ID
            value: jenkins-ci
          - key: JENKINS_HOME
            value: /var/lib/jenkins
  labelString: 'flyweight inspect'
  mode: EXCLUSIVE
  nodeProperties:
    - envVars:
        env:
          - key: JENKINS_HOME
            value: /var/jenkins_home
  numExecutors: 2
  projectNamingStrategy: "standard"
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 4
unclassified:
  location:
    adminAddress: infra@test.co
    url: ci-jenkins.test
```

I'm getting the following warnings:
```
ERROR: The file base.yaml is not valid. see errors :
WARNING:  - jenkins: Additional property globalNodeProperties is not allowed
WARNING:  - jenkins: Additional property nodeProperties is not allowed
WARNING:  - jenkins.disabledAdministrativeMonitors: Invalid type. Expected: string, given: array
WARNING:  - jenkins.projectNamingStrategy: Invalid type. Expected: object, given: string
WARNING:  - jenkins.remotingSecurity: Additional property enabled is not allowed
```

Any pointers on what the issue might be? 

This is using a `jcasc-schema.json` downloaded from one of our running Jenkins controllers using the latest `2.289.2` LTS release, and `configuration-as-code:1.5.1` plugin version.

The above config deploys fine via Jenkins itself...

Thanks in advance.
Gavin
